# Generated by Django 2.2 on 2020-03-17 22:22

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Property',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('address', models.CharField(max_length=200, validators=[django.core.validators.MinLengthValidator(1)])),
                ('city', models.CharField(max_length=50, validators=[django.core.validators.MinLengthValidator(1)])),
                ('state', models.CharField(max_length=2, validators=[django.core.validators.MinLengthValidator(2)])),
                ('zip', models.CharField(max_length=10, validators=[django.core.validators.MinLengthValidator(5)])),
            ],
        ),
    ]
