# Generated by Django 2.2 on 2020-03-12 21:30

from django.db import migrations, models
import properties.validators.property_validators


class Migration(migrations.Migration):

    dependencies = [
        ('properties', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='property',
            name='address',
            field=models.CharField(max_length=200, validators=[properties.validators.property_validators.address_min_length]),
        ),
        migrations.AlterField(
            model_name='property',
            name='city',
            field=models.CharField(max_length=50, validators=[properties.validators.property_validators.city_min_length]),
        ),
        migrations.AlterField(
            model_name='property',
            name='state',
            field=models.CharField(max_length=2, validators=[properties.validators.property_validators.state_length]),
        ),
        migrations.AlterField(
            model_name='property',
            name='zip',
            field=models.CharField(max_length=10, validators=[properties.validators.property_validators.zip_min_length]),
        ),
    ]
